fix: fixed abs() function to be invoked with named parameter "n"
camunda/feel-scala pull request #199
Opened 2020-10-09 06:40 UTC by daniel-shuy

## Description

* The `abs()` can now be invoked either with a named parameter `n` or `number`

## Related issues

closes #164

2020-10-09 06:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/feel-scala?pullRequest=199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/feel-scala?pullRequest=199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/feel-scala?pullRequest=199) it.</sub>

2020-10-12 04:35 UTC, saig0 requested changes
Thank you for your contribution @daniel-shuy :cookie: 

Looks good. I like your solution :+1: 
I have just some suggestions for minor improvements. Please have a look :)

2020-10-12 04:35 UTC, saig0 commented on src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala
> +    "abs" -> List(absFunctionNumber, absFunctionN),
We can declare the functions directly here.

```suggestion
    "abs" -> List(absFunction(paramName = "number"), absFunction(paramName = "n")),
```

2020-10-12 04:35 UTC, saig0 commented on src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala
> +
If the functions are declared in the list then we can remove them here.

```suggestion
```

2020-10-12 04:35 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala
> +  "abs() function" should "be invoked with named parameter number" in {
We can use the `it` statement to group the test cases.

```suggestion
  it should "be invoked with named parameter number" in {
```

2020-10-12 04:35 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala
> +  "abs() function" should "be invoked with named parameter n" in {
We can use the `it` statement to group the test cases.

```suggestion
  it should "be invoked with named parameter n" in {
```

2020-10-12 05:36 UTC, daniel-shuy commented
Done! Should I squash my commits?

2020-10-14 05:13 UTC, saig0 approved these changes
Thanks @daniel-shuy :tada:

2020-10-14 05:13 UTC, merged