bug(builtin-function): add 'm' and 'key' parameters support to get value
camunda/feel-scala pull request #337
Opened 2021-10-01 08:17 UTC by P3trur0

## Description

* Adds `m` and `key` parameters support to `get value`

## Related issues

closes #313

2021-10-01 08:48 UTC, saig0 commented
@P3trur0 thank you for your contribution :tada: 
I'll review your PR soon (~ beginning of next week).

2021-10-04 13:22 UTC, saig0 requested changes
@P3trur0 your PR looks good :+1: 

I've just a few minor suggestions. Please have a look.

2021-10-04 13:22 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
> +  "A get value function" should "return the value when arguments are named 'm' and 'key'" in {
:x: We should group test cases by using it. The test case will be in the same group as the previous test case (i.e. "A get value function").

```suggestion
  it should "return the value when arguments are named 'm' and 'key'" in {
```

2021-10-04 13:22 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
> +  "A get value function" should "return the value when arguments are named 'm' and 'key'" in {
:x: We should use the old parameter name in the previous test case. So, we can verify that the previous behavior still works.

2021-10-04 13:28 UTC, P3trur0 commented
@saig0 here you go, suggestions merged.

2021-10-05 05:02 UTC, saig0 approved these changes
@P3trur0 thanks :+1: Your PR is ready to merge :tada:

2021-10-05 05:11 UTC, merged