feat(Numeric) - Add random number function
camunda/feel-scala pull request #528
Opened 2022-10-04 21:04 UTC by kaaquist

## Description

* Added random number function and related tests and documentation. 

## Related issues

closes #506

2022-10-04 21:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/feel-scala?pullRequest=528) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/feel-scala?pullRequest=528) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/feel-scala?pullRequest=528) it.</sub>

2022-10-04 21:08 UTC, kaaquist commented
Still needed documentation and I also have a question in regards to test. I would like to test it the number returned is between 0.0f and 1.0f. I have created a test that I would expect would pass but I get an exception. 
Test:
```scala
it should "return a number between 0.0 and 1.0 " in {
    eval(" random number() ") should (be >= ValNumber(0.0) and be <= ValNumber(1.0))
}
```

Exception:
```text
overloaded method should with alternatives:
  (endWithWord: org.scalatest.matchers.dsl.EndWithWord)(implicit ev: org.camunda.feel.syntaxtree.Val <:< String): BuiltinNumberFunctionsTest.this.ResultOfEndWithWordForString <and>
  (startWithWord: org.scalatest.matchers.dsl.StartWithWord)(implicit ev: org.camunda.feel.syntaxtree.Val <:< String): BuiltinNumberFunctionsTest.this.ResultOfStartWithWordForString <and>
  (includeWord: org.scalatest.matchers.dsl.IncludeWord)(implicit ev: org.camunda.feel.syntaxtree.Val <:< String): BuiltinNumberFunctionsTest.this.ResultOfIncludeWordForString <and>
  (notExist: org.scalatest.matchers.dsl.ResultOfNotExist)(implicit existence: org.scalatest.enablers.Existence[org.camunda.feel.syntaxtree.Val]): org.scalatest.Assertion <and>
  (existWord: org.scalatest.matchers.dsl.ExistWord)(implicit existence: org.scalatest.enablers.Existence[org.camunda.feel.syntaxtree.Val]): org.scalatest.Assertion <and>
  (containWord: org.scalatest.matchers.dsl.ContainWord)org.scalatest.matchers.dsl.ResultOfContainWord[org.camunda.feel.syntaxtree.Val] <and>
  (haveWord: org.scalatest.matchers.dsl.HaveWord)BuiltinNumberFunctionsTest.this.ResultOfHaveWordForExtent[org.camunda.feel.syntaxtree.Val] <and>
  (beWord: org.scalatest.matchers.dsl.BeWord)BuiltinNumberFunctionsTest.this.ResultOfBeWordForAny[org.camunda.feel.syntaxtree.Val] <and>
  (inv: org.scalactic.TripleEqualsSupport.TripleEqualsInvocationOnSpread[org.camunda.feel.syntaxtree.Val])(implicit ev: Numeric[org.camunda.feel.syntaxtree.Val]): org.scalatest.Assertion <and>
  [U](inv: org.scalactic.TripleEqualsSupport.TripleEqualsInvocation[U])(implicit constraint: org.scalactic.CanEqual[org.camunda.feel.syntaxtree.Val,U]): org.scalatest.Assertion <and>
  (notWord: org.scalatest.matchers.dsl.NotWord)org.scalatest.matchers.dsl.ResultOfNotWordForAny[org.camunda.feel.syntaxtree.Val] <and>
  [TYPECLASS1[_], TYPECLASS2[_]](rightMatcherFactory2: org.scalatest.matchers.dsl.MatcherFactory2[org.camunda.feel.syntaxtree.Val,TYPECLASS1,TYPECLASS2])(implicit typeClass1: TYPECLASS1[org.camunda.feel.syntaxtree.Val], typeClass2: TYPECLASS2[org.camunda.feel.syntaxtree.Val]): org.scalatest.Assertion <and>
  [TYPECLASS1[_]](rightMatcherFactory1: org.scalatest.matchers.dsl.MatcherFactory1[org.camunda.feel.syntaxtree.Val,TYPECLASS1])(implicit typeClass1: TYPECLASS1[org.camunda.feel.syntaxtree.Val]): org.scalatest.Assertion <and>
  (rightMatcherX1: org.scalatest.matchers.Matcher[org.camunda.feel.syntaxtree.Val])org.scalatest.Assertion
 cannot be applied to (org.scalatest.matchers.Matcher[org.camunda.feel.syntaxtree.ValNumber])
    eval(" random number() ") should (be >= ValNumber(0.0) and be <= ValNumber(1.0))

```

2022-10-05 08:29 UTC, saig0 commented
> I would like to test it the number returned is between 0.0f and 1.0f. I have created a test that I would expect would pass but I get an exception.

Nice try. :+1: 

Instead, you could use a `match-case` and extract the number first. 

For example:

```
eval(" random number() ") match {
  case ValNumber(x) => x should (be >= 0 and be <= 1)  
  case other => fail()
}
```

2022-10-06 07:27 UTC, saig0 requested changes
@kaaquist thank you for your contribution. :tada: 

The changes look good. :+1: I have only a few minor comments.

2022-10-06 07:27 UTC, saig0 commented on src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala
> +        ValNumber(Random.nextFloat())
:wrench: We could use `nextDouble()` instead of `nextFloat()`. Numbers are represented as `BigDecimal`.

2022-10-06 12:01 UTC, merged

2022-10-06 12:04 UTC, saig0 commented
@kaaquist your PR is merged. :tada: Thank you for applying the hints. :cookie: 

---

This pull request counts toward the Hacktoberfest challenge. If you contributed four pull requests then you can complete your Camunda Hacktoberfest challenge [here](https://camunda.com/hacktoberfest2022/).