feat: create new assert function
camunda/feel-scala pull request #704
Opened 2023-09-05 09:27 UTC by nicpuppa

## Description

Create new `assert(value, condition)` function in order to allow users to verify if a variable met a certain condition, and return an error if the condition is not fulfilled. This function should help users to migrate to 8.3 easily if they rely on validation error.

Users can provide also a custom error message by `assert(value, condition, cause)`

## Related issues

closes #675

2023-09-05 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/feel-scala?pullRequest=704) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/feel-scala?pullRequest=704) before we can accept your contribution.<br/><hr/>**Nicola Puppa** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/feel-scala?pullRequest=704) it.</sub>

2023-09-07 12:19 UTC, saig0 requested changes
@nicpuppa well done. :tada: 

I found a few minor issues and one major issue. The function doesn't work in all cases. Please have a look at my comments. :cookie:

2023-09-07 12:21 UTC, saig0 commented
@nicpuppa it seems that the SLA bot doesn't like your commits. Please check if the email address of the commits match your GitHub account.

2023-09-07 14:00 UTC, nicpuppa commented on src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala
> +              error(EvaluationFailureType.FUNCTION_INVOCATION_FAILURE, s"Failed to invoke function '$name': $failure")
Thank you for the suggestion, you are right 💪

2023-09-07 14:00 UTC, nicpuppa commented on src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala
> +              ValError(failure)
This was a tricky one 👀 🤯

2023-09-07 14:01 UTC, nicpuppa commented
Hi @saig0 thanks for the review 🚀 

I applied all the suggestions, please have another look 👀  Sorry for the CLA, new pc 😂

2023-09-08 07:07 UTC, saig0 requested changes
@nicpuppa nice! :+1: 

One remaining task is to provide the custom failure message to the user. Please have a look at my comments. :cake:

2023-09-08 07:07 UTC, saig0 commented on src/main/scala/org/camunda/feel/FeelEngine.scala
> +      case _ if containsAssertionError(context) =>
:x: We should move this case to the top to ensure that we produce always the same failure message.

Currently, the failure message is different if the `assert()` function is wrapped inside another function or not.

2023-09-08 07:43 UTC, nicpuppa commented
Applied all suggestions, please have another look 👀

2023-09-08 08:35 UTC, saig0 approved these changes
@nicpuppa looks good. :+1: 

Before merging, please fix the test failure. I guess that you rebased on `main` but didn't take all the changes. On `main`, this test case is ignored.

2023-09-08 09:26 UTC, merged