Cooperation mode
camunda/feel-scala pull request #824
Opened 2024-04-08 13:09 UTC by vicmosin

## Description

* Continuing the discussion at [forum](https://forum.camunda.io/t/feelengines-cooperation-mode-while-performing-longrunning-and-resource-consuming-operations/51049), this simple change allows long-running feel evaluation/parsing processes be gracefully interrupted 

## Related issues

closes #823

2024-04-08 13:17 UTC, vicmosin commented
The solution allows consumers to execute the feel-engine parsing/evaluations on a separate threads and be able to cancel them itnerruptedly

2024-04-10 08:39 UTC, saig0 requested changes
@vicmosin your changes look good. :tada: I added a few comments we must address before merging. Please have a look.

2024-04-10 08:39 UTC, saig0 commented on src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala
> +    }
:wrench: We should add a comment to explain why we are checking for the interruption. 

It adds context for the next devs who is looking at this code.

2024-04-10 08:39 UTC, saig0 commented on src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala
:x: We should add a test case to verify that the interruption is working. And, to make sure that is will not be removed accidentally in the future.

2024-04-10 10:43 UTC, vicmosin commented on src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala
@saig0 Done, but not sure it's the proper implementation, I am not that familiar with scala

2024-04-11 11:51 UTC, vicmosin commented
Hey @saig0 , once merged can we get it as part of next minor release, let's say 1.17.6 ?

2024-04-15 14:14 UTC, vicmosin commented
@saig0 anything else I should adjust?

2024-04-18 07:29 UTC, saig0 requested changes
@vicmosin very nice. :rocket: I see some improvements for the test case. Please have a look. :cookie:

2024-04-18 07:29 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/interpreter/InterpreterInterruptionTest.scala
> +    with EvaluationResultMatchers {
:wrench: `EvaluationResultMatchers` is not used. We can remove it.

```suggestion
class InterpreterInterruptionTest extends AnyFlatSpec with Matchers with FeelEngineTest {
```

2024-04-18 07:29 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/interpreter/InterpreterInterruptionTest.scala
> +    Thread.sleep(1000) // Let evaluation start
:wrench: We could decrease the waiting time to speed up the test. We don't need to wait so long. 

```suggestion
    Thread.sleep(100) // Let evaluation start
```

2024-04-18 07:29 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/interpreter/InterpreterInterruptionTest.scala
> +    countDownLatch.await()
:wrench: We could use the return value of `await()` to verify that the thread was interrupted. 

```suggestion
    val wasInterrupted = countDownLatch.await(1, TimeUnit.SECONDS)

    wasInterrupted should be(true)
```

2024-04-18 07:29 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/interpreter/InterpreterInterruptionTest.scala
> +    assert(!threadDump.contains("FeelInterpreter"))
:wrench: Using a thread dump to verify the interruption is a nice idea. However, it is a bit too much for this test case. It is enough to verify that the thread was interrupted by checking the count-down-latch.

Let's remove this part to keep it easy.

2024-04-18 08:16 UTC, vicmosin commented
@saig0 done

2024-04-18 08:30 UTC, saig0 approved these changes
@vicmosin great. :zap: LGTM. :tada:

2024-04-18 08:41 UTC, merged

2024-04-18 10:02 UTC, vicmosin commented
@saig0 when to wait for a release, approx obviously?

2024-04-18 10:23 UTC, saig0 commented
/backport

2024-04-18 10:23 UTC, saig0 commented
Successfully created backport PR for `1.17`:
- #830

2024-04-18 10:24 UTC, saig0 commented
@vicmosin I will build a patch release for 1.17 tomorrow. :building_construction: