feat: add function to check if a list is empty
camunda/feel-scala pull request #851
Opened 2024-05-22 00:31 UTC by skayliu

## Description

Add a new function to check if a list is empty.
* 

## Related issues

closes #805

2024-05-22 07:53 UTC, saig0 requested changes
@skayliu thank you for your contribution. :tada: 

The changes look good. I have a few minor suggestions. Please have a look. :cookie:

2024-05-22 07:53 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
> +    eval(" is empty([ ]) ") should be(ValBoolean(true))
:wrench: This test case is duplicated. `[]` is the same as `[ ]`. 

We can remove one of them.

2024-05-22 07:53 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
> +  "A list is empty() function" should "return if the list is or not empty" in {
:wrench: Improve wording.

```suggestion
  "A list is empty() function" should "return if the list is empty" in {
```

2024-05-22 07:53 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
> +    eval(" is empty([1,2,3]) ") should be(ValBoolean(false))
:wrench: We should add one more test case with named parameters to ensure that the named parameter doesn't change.

```
eval(" is empty(list: [1]) ") should be(ValBoolean(false))
```

2024-05-22 12:53 UTC, skayliu commented
Hey, @saig0, it's done,  do i need to rebase to main?

2024-05-23 04:10 UTC, saig0 approved these changes
@skayliu your PR is ready to merge. :rocket:

2024-05-23 04:13 UTC, merged