feat(builtin): add partition function
camunda/feel-scala pull request #950
Opened 2024-11-11 18:23 UTC by lzgabel

## Description
* This PR adds a built in list function `partition(list, size)`. 
* Support for splitting an array into equals sub arrays each with the maximum number of elements defined by the `size` argument.  

## Related issues
closes #881

2024-11-13 12:08 UTC, saig0 commented
@lzgabel awesome. Thank you for your contribution. :tada: 

I'll review your changes in the next few days. Please take a look at the [contribution guidelines](https://github.com/camunda/feel-scala/blob/main/CONTRIBUTING.md#adding-a-new-built-in-function) and check if you followed the guide. :eyes:

2024-11-15 12:41 UTC, saig0 requested changes
@lzgabel your changes look great. :+1: 

I added a few comments for minor improvements. Please have a look. :cookie:

2024-11-15 12:41 UTC, saig0 commented on src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala
> +          ValNull
:wrench: We could return an error to explain why the result is `null`.

```suggestion
          ValError(s"'size' should be greater than zero but was '$size'")
```

Refer to the [guidelines](https://github.com/camunda/feel-scala/blob/main/CONTRIBUTING.md#adding-a-new-built-in-function).

2024-11-15 12:41 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
> +    )
:wrench: We should add another case that invokes the function with named parameters.

```
evaluateExpression(" partition(list: [1,2,3,4,5], size: 2) ")
```

Refer to the [guidelines](https://github.com/camunda/feel-scala/blob/main/CONTRIBUTING.md#adding-a-new-built-in-function).

2024-11-15 12:41 UTC, saig0 commented on src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
> +    evaluateExpression(" partition([1,2], 0) ") should returnNull()
:wrench: After returning an error from the function, we could verify the error in the test case.

```
    evaluateExpression(" partition([1,2], 0) ") should (
      returnNull() and reportFailure(
        FUNCTION_INVOCATION_FAILURE,
        "Failed to invoke function 'partition': 'size' should be greater than zero but was '0'"
      )
    )
```

2024-11-18 11:16 UTC, lzgabel commented
Hi @saig0. I have applied your suggestions and squashed the commits. Please check this out. 🙇

2024-11-19 12:32 UTC, saig0 approved these changes
@lzgabel LGTM. Great work! :rocket: 

-----

Please follow up and add the new function to the C8 documentation. Refer to the [guidelines](https://github.com/camunda/feel-scala/blob/main/CONTRIBUTING.md#adding-a-new-built-in-function).

2024-11-19 12:35 UTC, merged